tap "cjbassi/ytop"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "python@3.9"
brew "awscli"
brew "bat"
brew "cmake"
brew "coreutils"
brew "deno"
brew "exa"
brew "fzf"
brew "gcc"
brew "git"
brew "gnupg"
brew "gnuplot"
brew "go"
brew "golangci-lint"
brew "graphviz"
brew "imagemagick"
brew "jq"
brew "llvm"
brew "mas"
brew "neovim"
brew "nodebrew"
brew "ripgrep"
brew "terraform"
brew "tig"
brew "tmux"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "cjbassi/ytop/ytop"
brew "hashicorp/tap/terraform-ls"
cask "adobe-acrobat-reader"
cask "alacritty"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "iterm2"
cask "keycastr"
cask "mactex"
cask "slack"
cask "visual-studio-code"
mas "AmorphousDiskMark", id: 1168254295
mas "GeoGebra Classic 6", id: 1182481622
mas "LINE", id: 539883307
mas "Logic Pro", id: 634148309
mas "Magnet", id: 441258766
mas "Pages", id: 409201541
mas "PicGIF Lite", id: 844918735
mas "Skitch", id: 425955336
mas "Xcode", id: 497799835
