FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /root
ENV DENO_VERSION=1.14.1
ENV LANG="ja_JP.UTF-8" LANGUAGE="ja_JP:ja" LC_ALL="ja_JP.UTF-8"

RUN apt-get update && \
    apt-get install -y -q --no-install-recommends \
      curl ca-certificates && \
    curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh && \
    chmod +x nodesource_setup.sh && ./nodesource_setup.sh && \
    rm -f ./nodesource_setup.sh

RUN apt-get update && \
    apt-get install -y -q --no-install-recommends software-properties-common && \
    apt-get update && \
    apt-get install -y -q --allow-unauthenticated --no-install-recommends \
      curl \
      gcc \
      g++ \
      git \
      nodejs \
      python3-dev \
      python3-pip \
      unzip \
      fzf \
      gosu \
      language-pack-ja && \
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage && \
    chmod +x ./nvim.appimage && \
    ./nvim.appimage --appimage-extract && rm -f ./nvim.appimage && \
    mv squashfs-root / && \
    ln -s /squashfs-root/AppRun /usr/bin/nvim && \
    curl -fsSL https://github.com/denoland/deno/releases/download/v1.14.1/deno-x86_64-unknown-linux-gnu.zip --output deno.zip && \
    unzip deno.zip && \
    chmod 777 deno && \
    mv deno /usr/local/bin/deno

RUN pip3 install --upgrade pip neovim pynvim && \
    rm -rf /root/.cache && \
    npm install -g neovim

RUN useradd -s /bin/bash -m user
USER user
WORKDIR /home/user
COPY --chown=user nvim .config/nvim
WORKDIR .config/coc/extensions
RUN    nvim +:UpdateRemotePlugins +qa

RUN npm install \
    coc-word \
    coc-diagnostic \
    coc-tsserver \
    coc-rls \
    coc-json \
    coc-jedi \
    coc-go \
    coc-clangd \
    coc-json \
    coc-css \
    coc-cssmodules \
    coc-toml \
    coc-sql \
    coc-markdownlint \
    coc-yaml \
    --global-style --ignore-scripts --no-bin-links --no-package-lock --production --legacy-peer-deps

USER root
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
