#!/bin/zsh
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias gp='git-foresta --all --style=10 | less -RSX'
alias aca='acc submit a.cpp'
alias va='nvim a.cpp'
alias ojt='oj t'
alias ls='exa --icons'
alias vf='vim $(fzf --preview "head -100 {}")'
alias t='tig'
