name: CD
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_PROFILE_NAME: builder

jobs:
  copy:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        profile:
          - work
          - personal
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Build package
        run: nix build .#darwinConfigurations.${{ matrix.profile }}.system --accept-flake-config

      - name: Sign package with secret key
        env:
          BINARY_CACHE_SECRET_KEY: ${{ secrets.BINARY_CACHE_SECRET_KEY }}
        run: |
          echo $BINARY_CACHE_SECRET_KEY > ./secret.key
          nix store sign --recursive --key-file ./secret.key ./result

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          nix shell nixpkgs#awscli --command aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $AWS_PROFILE_NAME
          nix shell nixpkgs#awscli --command aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $AWS_PROFILE_NAME

      - name: Copy package
        env:
          S3_API_ENDPOINT: ${{ secrets.S3_API_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: nix copy --to s3://$S3_BUCKET\?profile=$AWS_PROFILE_NAME\&endpoint=$S3_API_ENDPOINT\&compression=zstd ./result
